Add remaining tests to Mac/Windows pipeline
redhat-developer/vscode-extension-tester pull request #620
Opened 2023-02-07 21:33 UTC by mlorinc

Signed-off-by: Marian Lorinc <mlorinc@redhat.com>

Before submitting your PR, please review the following checklist:

- [ ] **CONSIDER** adding a new test if your PR resolves an issue.
- [ ] **DO** keep pull requests small so they can be easily reviewed.
- [ ] **DO** make sure tests pass.
- [ ] **DO** make sure any public APIs changes are documented.
- [ ] **DO** make sure not to introduce any compiler warnings.

Before merging the PR:
- [ ] **CHECK** continous integration of main branch is green.
- [ ] **CHECK** pull request check job is green.
- [ ] **CHECK** all pull request questions/requests are resolved.
- [ ] **WAIT** till PR is approved by at least 1 committer.

2023-02-10 13:42 UTC, ssbarnea approved these changes

2023-02-14 10:29 UTC, djelinek commented
I agree we need to unified workflows for all architectures it is on my backlog too, but is not as simple as that.. 

we need to do in two iterations for each os (win, mac) because each will need some extra work on tests side to have it fully working

2023-02-14 10:29 UTC, djelinek requested changes
mac and win will currently fail.. it is not that simple change

2023-02-16 23:51 UTC, djelinek commented
closing for now - please reopen for each OS (win, mac) separate Pr which will contain also tests fixes

2023-02-16 23:51 UTC, closed without merging