Fix getCodeLenses logic
redhat-developer/vscode-extension-tester pull request #903
Opened 2023-08-09 10:33 UTC by unsortedhashsets

Hi, 

Changed logic:

1. getCodeLenses, xpath changed from `.//span[contains(@widgetid, 'codelens.widget')]` to `.//span[contains(@widgetid, 'codelens.widget')]/a[@id]` to select all codelenses and not codelenses container
2. CodeLens, constructor changed from `super(element.findElement(By.css('a')), editor);` to `super(element, editor);`

So these changes should fix reported bug #902 

Check for new xpath ->
![xpath-check](https://github.com/redhat-developer/vscode-extension-tester/assets/46084942/0521eb8a-5e7f-4e3f-a3b7-e0242089ae82)

---

Before submitting your PR, please review the following checklist:

~- **CONSIDER** adding a new test if your PR resolves an issue.~ not possible to test due [codelens-sample](https://github.com/microsoft/vscode-extension-samples/tree/ead2640188c31d12ad07ed4d3c0d47d5b54a23c8/codelens-sample) limitation
- [X] **DO** keep pull requests small so they can be easily reviewed.
- [X] **DO** make sure tests pass.
~- **DO** make sure any public APIs changes are documented.~ No changes 
- [X] **DO** make sure not to introduce any compiler warnings.

Before merging the PR:
- [ ] **CHECK** continous integration of main branch is green.
- [ ] **CHECK** pull request check job is green.
- [ ] **CHECK** all pull request questions/requests are resolved.
- [ ] **WAIT** till PR is approved by at least 1 committer.

2023-08-21 19:31 UTC, djelinek approved these changes

2023-08-21 19:33 UTC, djelinek requested changes

2023-08-21 19:33 UTC, djelinek commented on page-objects/src/components/editor/TextEditor.ts
>      constructor(element: WebElement, editor: TextEditor) {
by this change, the constructor becomes useless and can be removed

2023-08-22 09:35 UTC, djelinek commented
@unsortedhashsets it would be nice to also modify codelens provider (https://github.com/redhat-developer/vscode-extension-tester/blob/main/test/test-project/src/codelensProvider.ts) and tests to check also more codelens are now possible to work with

2023-08-22 09:37 UTC, unsortedhashsets commented
> @unsortedhashsets it would be nice to also modify codelens provider (https://github.com/redhat-developer/vscode-extension-tester/blob/main/test/test-project/src/codelensProvider.ts) and tests to check also more codelens are now possible to work with

will try, thanks!

2023-08-22 11:58 UTC, merged